packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: 4.0.14
  "@t3-oss/env-core": 0.13.8
catalogs:
 
onlyBuiltDependencies:
  - esbuild
