packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@sinclair/typebox": ^0.34
  "@t3-oss/env-core": 0.13.8
  dotenv-cli: 10.0.0
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  tsx: 4.20.3
  typescript: ^5.8.3
  viem: ^2.33.2
  zod: 4.0.14
catalogs:
 
onlyBuiltDependencies:
  - esbuild
